stages:
  retrain:
    cmd: python src/retrain.py
    deps:
    - src/retrain.py
    params:
    - train.batch_size
    - train.dropout
    - train.hidden_units
    - train.lr
    - train.num_epochs
    metrics:
    - dvclive/metrics.json:
        cache: false
